apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-test
    spec:
      containers:
      - name: kube-test
        image: gcr.io/qubit-infra-stg/kube-test
